<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <SelfContained>true</SelfContained>
    <!-- <UseAppHost>true</UseAppHost>  -->
    <EnableDynamicCodeSupport>true</EnableDynamicCodeSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.8.2" />
    <PackageReference Include="AngleSharp.Css" Version="1.1.3-beta.330" />
    <PackageReference Include="Microsoft.Z3" Version="4.12.2" />
  </ItemGroup>
</Project>
